const axios = require('axios');

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || '';
const MODEL = process.env.GEMINI_MODEL || 'gemini-1.5-flash';

async function generateQuizFromPrompt({ prompt, numQuestions = 10, difficulty = 'medium' }) {
  if (!GEMINI_API_KEY) {
    throw new Error('GEMINI_API_KEY missing');
  }

  const systemPrompt = `
You are an AI quiz generator. Produce ${numQuestions} multiple choice questions with 4 options each.
Include correct_answer as the zero-based index, time_limit (seconds), points (int), and short explanation.
Difficulty: ${difficulty}.
Return JSON: { title, description, category, difficulty, questions: [ { id, question, type, options, correct_answer, time_limit, points, explanation } ] }.
`;

  const body = {
    contents: [
      {
        role: 'user',
        parts: [{ text: `${systemPrompt}\nSource:\n${prompt}` }]
      }
    ]
  };

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${GEMINI_API_KEY}`;

  const { data } = await axios.post(url, body, {
    headers: { 'Content-Type': 'application/json' },
    timeout: 120000
  });

  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text || '';
  const parsed = safeJson(text);
  if (!parsed || !parsed.questions) {
    throw new Error('AI response missing questions');
  }
  return normalizeQuiz(parsed);
}

function safeJson(raw) {
  try {
    const cleaned = raw.trim().replace(/```json|```/g, '');
    return JSON.parse(cleaned);
  } catch (err) {
    return null;
  }
}

function normalizeQuiz(raw) {
  return {
    title: raw.title || 'AI Generated Quiz',
    description: raw.description || 'Generated by AI',
    category: raw.category || 'ai_generated',
    difficulty: raw.difficulty || 'medium',
    questions: (raw.questions || []).map((q, idx) => ({
      id: q.id || `q${idx + 1}`,
      question: q.question,
      type: q.type || 'multiple_choice',
      options: q.options || ['Option A', 'Option B', 'Option C', 'Option D'],
      correct_answer: typeof q.correct_answer === 'number' ? q.correct_answer : 0,
      time_limit: q.time_limit || 20,
      points: q.points || 1000,
      explanation: q.explanation || ''
    }))
  };
}

module.exports = {
  generateQuizFromPrompt
};




